### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Patrik-svobodik** [supermerill/Slic3r#28]
Hi, I am unable to build the masterPE branch, I am following the Prusa manual, I am able to build the original repo just fine, this is the error:

make[2]: *** [src/libslic3r/CMakeFiles/libslic3r.dir/pchheader.cpp.o] Error 1
make[1]: *** [src/libslic3r/CMakeFiles/libslic3r.dir/all] Error 2
make: *** [all] Error 2

**Comment by supermerill** [comment]
use the commit 29d2d80202e017315cbeb1c4a671f5863955db5d

i tried to merge but i didn't have the time to build. I tried then to set the label on the "good" commit, but no luck with only the web interface

**Comment by supermerill** [comment]
visual studio 2013?

**Comment by Patrik-svobodik** [comment]
@supermerill did you look into it?

**Comment by supermerill** [comment]
I just finished building the materPE:head. I has to add some std: in some places. I didn't had the time to push it before taking my plane, sorry.

I didn't encounter the " 'string.h' file not found". Maybe it's a problem on your system: your make didn't find it.

**Comment by Patrik-svobodik** [comment]
Hi, when will you push it out?

**Comment by supermerill** [comment]
now ;-p

**Comment by Patrik-svobodik** [comment]
I am still unable to build it, even with the newest commits, there is
something weird
čt 21. 2. 2019 v 16:12 odesílatel Merill <notifications@github.com> napsal:

**Comment by uniacke1** [comment]
Trying to build on Linux here with Boost 1.66, made a few tweaks for my system but fails at linking step, I get the error undefined reference to `boost::filesystem::path_traits::convert(wchar_t const*, wchar_t const*, std::string&, std::codecvt<wchar_t, char, __mbstate_t> const&)'

both Boost:fileysytem and boost:system libraries and devel packages installed.

**Comment by uniacke1** [comment]
Update - solved. My issue was caused by differing ABIs on the compiler and my system's boost libraries from being built with different versions of gcc.

**Comment by supermerill** [comment]
I have much less difficulties setting up the dev toolchain for compiling for 2013 & 2017 now. I will close that issue. Open a new one if a similar problem arise again.
