### ISSUE TITLE
boost::process::ipstream does not seem to exist in boost 1.88

### ISSUE THREAD

**Issue by gyscos** [supermerill/Slic3r#4639]
### What happened?

Trying to build this package on archlinux with boost 1.88:

```
/var/ab/superslicer/src/SuperSlicer-2.5.59.13/src/libslic3r/GCode/PostProcessor.cpp: In function ‘int run_script(const std::string&, const std::string&, std::string&)’:
/var/ab/superslicer/src/SuperSlicer-2.5.59.13/src/libslic3r/GCode/PostProcessor.cpp:224:14: error: ‘ipstream’ is not a member of ‘process’
  224 |     process::ipstream istd_err;
      |              ^~~~~~~~
/var/ab/superslicer/src/SuperSlicer-2.5.59.13/src/libslic3r/GCode/PostProcessor.cpp:225:14: error: ‘child’ is not a member of ‘process’
  225 |     process::child child(shell, "-c", command_line, process::std_err > istd_err);
      |              ^~~~~
```

These might possibly need different headers.

### Project file & How to reproduce

Try to build with boost 1.88 installed on the system.

### Version

2.5.59.13

### Operating system

ArchLinux

**Comment by supermerill** [comment]
currently I only support boost 1.83
This dependency will be updated when I'll merge with 1.9/1.10

**Comment by supermerill** [comment]
see https://github.com/supermerill/SuperSlicer/pull/4635
to compile with newer version of boost.
